@echo off
setlocal EnableExtensions EnableDelayedExpansion

set "SCRIPT_DIR=%~dp0"
set "ConfigFile=%SCRIPT_DIR%apt.config.cmd"
if not "%~1"=="" set "ConfigFile=%~1"
set "TempRoot=%TEMP%\apt_replay_batch_%RANDOM%_%RANDOM%"
mkdir "%TempRoot%" >nul 2>&1

if exist "%ConfigFile%" (
  echo [INFO] Loading batch config from "%ConfigFile%"
  call "%ConfigFile%"
) else (
  echo [ERROR] Config file not found: "%ConfigFile%"
  endlocal & exit /b 2
)

set "ReplayListArg=%REPLAY_LIST%"
if not defined ReplayListArg set "ReplayListArg=REPLAY_LIST in %ConfigFile%"
if not "%~2"=="" set "ReplayListArg=%~2"

if not defined ReplayListArg (
  echo [ERROR] REPLAY_LIST is empty. Set REPLAY_LIST in config or pass it as arg2.
  echo [INFO] REPLAY_LIST accepts semicolon-separated replay paths, or a path to a .txt/.list file.
  endlocal & exit /b 2
)

set "ReplayInputFile="
if exist "%ReplayListArg%" set "ReplayInputFile=%ReplayListArg%"

set /a Total=0
set /a Failed=0
set "SummaryFile=%TempRoot%\summary.txt"

echo [INFO] Replay input: "%ReplayListArg%"
if defined ReplayInputFile echo [INFO] Replay input file: "%ReplayInputFile%"
echo [INFO] Temp config dir: "%TempRoot%"
echo.

if defined ReplayInputFile (
  for /f "usebackq delims=" %%R in ("%ReplayInputFile%") do (
    set "ReplayLine=%%R"
    if not "!ReplayLine!"=="" if not "!ReplayLine:~0,1!"=="#" (
      set /a Total+=1
      call :RunOneReplay "!ReplayLine!" !Total!
      if errorlevel 1 set /a Failed+=1
    )
  )
) else (
  set "RemainingReplayList=%ReplayListArg%"
  call :RunInlineReplayList
)

echo.
echo [INFO] Batch finished. Total=!Total! Failed=!Failed!
echo [INFO] Summary: "%SummaryFile%"

if "!Total!"=="0" (
  echo [ERROR] No replay entries found in "%ReplayListArg%"
  endlocal & exit /b 2
)

if not "!Failed!"=="0" (
  endlocal & exit /b 1
)

endlocal & exit /b 0

:RunOneReplay
set "ReplayPath=%~1"
set "ReplayIndex=%~2"
for %%I in ("%ReplayPath%") do set "ReplayName=%%~nI"
if not defined ReplayName set "ReplayName=Replay%ReplayIndex%"

set "TempConfig=%TempRoot%\apt_%ReplayIndex%.config.cmd"
copy /Y "%ConfigFile%" "%TempConfig%" >nul
>> "%TempConfig%" echo rem Generated by run_replay_batch.bat
>> "%TempConfig%" echo set "REPLAY_PATH=%ReplayPath%"

echo [INFO] [!ReplayIndex!] Running replay: "%ReplayPath%"
call "%SCRIPT_DIR%run_replay.bat" "%TempConfig%"
set "RC=%ERRORLEVEL%"

if "%RC%"=="0" (
  echo PASS [%ReplayIndex%] "%ReplayPath%" >> "%SummaryFile%"
  echo [INFO] [!ReplayIndex!] PASS
) else (
  echo FAIL [%ReplayIndex%] rc=%RC% "%ReplayPath%" >> "%SummaryFile%"
  echo [ERROR] [!ReplayIndex!] FAIL rc=%RC%
)
echo.
exit /b %RC%

:RunInlineReplayList
if not defined RemainingReplayList exit /b 0
set "ReplayLine="
for /f "tokens=1* delims=;" %%A in ("!RemainingReplayList!") do (
  set "ReplayLine=%%~A"
  set "RemainingReplayList=%%~B"
)
if not "!ReplayLine!"=="" if not "!ReplayLine:~0,1!"=="#" (
  set /a Total+=1
  call :RunOneReplay "!ReplayLine!" !Total!
  if errorlevel 1 set /a Failed+=1
)
if defined RemainingReplayList goto RunInlineReplayList
exit /b 0
